import { Product, Category, User, Order } from '../types';

export const initialCategories: Category[] = [
  {
    _id: 'cat_1',
    name: 'Mobiles & Tablets',
    slug: 'mobiles-tablets',
    description: 'Latest flagship smartphones, 5G devices, and tablets with prime delivery.',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    order: 1,
  },
  {
    _id: 'cat_2',
    name: 'Laptops & Computers',
    slug: 'laptops-computers',
    description: 'High performance gaming rigs, ultrabooks, monitors, and accessories.',
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80',
    order: 2,
  },
  {
    _id: 'cat_3',
    name: 'Audio & Headphones',
    slug: 'audio-headphones',
    description: 'Noise cancelling headphones, true wireless earbuds, and home soundbars.',
    icon: 'Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    order: 3,
  },
  {
    _id: 'cat_4',
    name: 'Fashion & Apparel',
    slug: 'fashion-apparel',
    description: 'Trending styles, casual wear, shoes, and luxury timepieces.',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&auto=format&fit=crop&q=80',
    order: 4,
  },
  {
    _id: 'cat_5',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Smart kitchen appliances, coffee makers, cookware, and modern furniture.',
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    order: 5,
  },
  {
    _id: 'cat_6',
    name: 'Smart Watches',
    slug: 'smart-watches',
    description: 'Fitness trackers, AMOLED smartwatches, and health monitors.',
    icon: 'Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    order: 6,
  },
];

export const initialProducts: Product[] = [
  {
    _id: 'prod_1',
    title: 'Apple iPhone 15 Pro (128 GB) - Natural Titanium',
    slug: 'apple-iphone-15-pro-128gb-natural-titanium',
    description: 'iPhone 15 Pro. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most versatile iPhone camera system ever.',
    brand: 'Apple',
    category: initialCategories[0],
    categorySlug: 'mobiles-tablets',
    price: 129900,
    originalPrice: 134900,
    discountPercentage: 4,
    rating: 4.8,
    numReviews: 2450,
    stock: 25,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'storage', name: '128 GB', priceDelta: 0, stock: 15, sku: 'IP15P-128-NAT' },
      { type: 'storage', name: '256 GB', priceDelta: 10000, stock: 20, sku: 'IP15P-256-NAT' },
      { type: 'storage', name: '512 GB', priceDelta: 30000, stock: 8, sku: 'IP15P-512-NAT' },
      { type: 'color', name: 'Natural Titanium', priceDelta: 0, stock: 15, sku: 'IP15P-NAT' },
      { type: 'color', name: 'Blue Titanium', priceDelta: 0, stock: 10, sku: 'IP15P-BLU' },
      { type: 'color', name: 'Black Titanium', priceDelta: 0, stock: 12, sku: 'IP15P-BLK' },
    ],
    isPrimeEligible: true,
    isBestSeller: true,
    isAmazonChoice: false,
    isLightningDeal: true,
    lightningDealEndsAt: new Date(Date.now() + 86400000).toISOString(),
    lightningDealClaimedPercentage: 68,
    features: [
      'FORGED IN TITANIUM — Strong and light aerospace-grade titanium design.',
      'A17 PRO CHIP — A monster win for gaming with next-level graphics.',
      'POWERFUL PRO CAMERA SYSTEM — 7 pro lenses with 48MP Main camera.',
      'CUSTOMIZABLE ACTION BUTTON — Fast track to your favourite feature.',
    ],
    specifications: {
      Display: '6.1-inch Super Retina XDR display with ProMotion 120Hz',
      Chip: 'A17 Pro chip with 6-core GPU',
      Camera: '48MP Main + 12MP Ultra Wide + 12MP 3x Telephoto',
      Connector: 'USB-C with USB 3 speeds up to 10Gb/s',
    },
    tags: ['iphone', 'apple', 'smartphone', '5g', 'titanium', 'camera'],
  },
  {
    _id: 'prod_2',
    title: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 256GB Storage)',
    slug: 'samsung-galaxy-s24-ultra-5g-titanium-gray-256gb',
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity, productivity, and possibility. Includes built-in S Pen.',
    brand: 'Samsung',
    category: initialCategories[0],
    categorySlug: 'mobiles-tablets',
    price: 129999,
    originalPrice: 139999,
    discountPercentage: 7,
    rating: 4.7,
    numReviews: 1890,
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'storage', name: '256 GB', priceDelta: 0, stock: 12, sku: 'S24U-256-GRY' },
      { type: 'storage', name: '512 GB', priceDelta: 15000, stock: 6, sku: 'S24U-512-GRY' },
      { type: 'color', name: 'Titanium Gray', priceDelta: 0, stock: 10, sku: 'S24U-GRY' },
      { type: 'color', name: 'Titanium Black', priceDelta: 0, stock: 8, sku: 'S24U-BLK' },
    ],
    isPrimeEligible: true,
    isBestSeller: false,
    isAmazonChoice: true,
    isLightningDeal: false,
    features: [
      'GALAXY AI IS HERE — Circle to Search with Google, Live Translate, and Note Assist.',
      'TITANIUM ARMOR — Durable shield of titanium built right into the frame.',
      '200MP CAMERA & QUAD TELE SYSTEM — Unrivaled zoom clarity from 1x to 100x.',
      'BUILT-IN S PEN — Write, tap, and navigate with high precision.',
    ],
    specifications: {
      Display: '6.8-inch Dynamic AMOLED 2X, 2600 nits peak brightness',
      Processor: 'Snapdragon 8 Gen 3 for Galaxy',
      Battery: '5,000 mAh with 45W Fast Charging',
      Stylus: 'Integrated Bluetooth S Pen',
    },
    tags: ['samsung', 'galaxy', 's24 ultra', 'ai', 'camera', 'android'],
  },
  {
    _id: 'prod_3',
    title: 'OnePlus 12 (Silky Black, 16GB RAM, 512GB Storage)',
    slug: 'oneplus-12-silky-black-512gb',
    description: 'The OnePlus 12 is powered by Qualcomm Snapdragon 8 Gen 3 with 4th Gen Hasselblad Camera System for Mobile and ultra-fast 100W SUPERVOOC charging.',
    brand: 'OnePlus',
    category: initialCategories[0],
    categorySlug: 'mobiles-tablets',
    price: 69999,
    originalPrice: 74999,
    discountPercentage: 7,
    rating: 4.6,
    numReviews: 1240,
    stock: 30,
    images: [
      'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'storage', name: '256 GB', priceDelta: -5000, stock: 15, sku: 'OP12-256-BLK' },
      { type: 'storage', name: '512 GB', priceDelta: 0, stock: 15, sku: 'OP12-512-BLK' },
      { type: 'color', name: 'Silky Black', priceDelta: 0, stock: 20, sku: 'OP12-BLK' },
      { type: 'color', name: 'Flowy Emerald', priceDelta: 0, stock: 10, sku: 'OP12-EMR' },
    ],
    isPrimeEligible: true,
    isBestSeller: false,
    isAmazonChoice: true,
    isLightningDeal: false,
    features: [
      'Snapdragon 8 Gen 3 Mobile Platform with up to 16GB LPDDR5X RAM.',
      '4th Gen Hasselblad Camera System with 64MP 3X Periscope Telephoto.',
      '2K 120Hz ProXDR Display with advanced LTPO.',
      '100W SUPERVOOC wired and 50W AIRVOOC wireless charging.',
    ],
    specifications: {
      Display: '6.82-inch 2K 120Hz ProXDR AMOLED',
      RAM: '16 GB LPDDR5X',
      Battery: '5400 mAh Dual-cell battery',
      Charging: '100W SUPERVOOC wired charger included in box',
    },
    tags: ['oneplus', 'oneplus 12', 'hasselblad', 'fast charging', 'android'],
  },
  {
    _id: 'prod_4',
    title: 'Apple MacBook Pro 16" M3 Max (36GB Unified Memory, 1TB SSD) - Space Black',
    slug: 'apple-macbook-pro-16-m3-max-space-black',
    description: 'Mind-blowing performance with the M3 Max chip. Up to 22 hours of battery life. Liquid Retina XDR display with extreme dynamic range. Space Black finish.',
    brand: 'Apple',
    category: initialCategories[1],
    categorySlug: 'laptops-computers',
    price: 349900,
    originalPrice: 369900,
    discountPercentage: 5,
    rating: 4.9,
    numReviews: 870,
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'storage', name: '1 TB SSD', priceDelta: 0, stock: 8, sku: 'MBP16-M3M-1TB' },
      { type: 'storage', name: '2 TB SSD', priceDelta: 40000, stock: 4, sku: 'MBP16-M3M-2TB' },
      { type: 'color', name: 'Space Black', priceDelta: 0, stock: 7, sku: 'MBP16-BLK' },
      { type: 'color', name: 'Silver', priceDelta: 0, stock: 5, sku: 'MBP16-SLV' },
    ],
    isPrimeEligible: true,
    isBestSeller: true,
    isAmazonChoice: false,
    isLightningDeal: false,
    features: [
      'SUPERCHARGED BY M3 MAX — 14-core CPU and 30-core GPU for monster 3D and code builds.',
      'UP TO 22 HOURS OF BATTERY LIFE — Efficiency that goes all day.',
      'BRILLIANT PRO DISPLAY — 16.2-inch Liquid Retina XDR with 1000 nits sustained brightness.',
      'PRO CONNECTIVITY — Three Thunderbolt 4 ports, HDMI port, SDXC card slot, MagSafe 3.',
    ],
    specifications: {
      Display: '16.2-inch Liquid Retina XDR, 3456x2234 resolution, 120Hz ProMotion',
      Memory: '36GB Unified Memory',
      Storage: '1TB Superfast SSD',
      Weight: '2.16 kg',
    },
    tags: ['macbook', 'apple', 'm3 max', 'laptop', 'developer', 'space black'],
  },
  {
    _id: 'prod_5',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones - Silver',
    slug: 'sony-wh-1000xm5-wireless-headphones-silver',
    description: 'Industry-leading noise canceling with two processors and 8 microphones. Magnificent sound, engineered to perfection with the integrated V1 processor and LDAC high-res audio.',
    brand: 'Sony',
    category: initialCategories[2],
    categorySlug: 'audio-headphones',
    price: 29990,
    originalPrice: 34990,
    discountPercentage: 14,
    rating: 4.7,
    numReviews: 4120,
    stock: 40,
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'color', name: 'Silver', priceDelta: 0, stock: 20, sku: 'WH5-SLV' },
      { type: 'color', name: 'Black', priceDelta: 0, stock: 20, sku: 'WH5-BLK' },
      { type: 'color', name: 'Midnight Blue', priceDelta: 1000, stock: 10, sku: 'WH5-BLU' },
    ],
    isPrimeEligible: true,
    isBestSeller: true,
    isAmazonChoice: true,
    isLightningDeal: true,
    lightningDealEndsAt: new Date(Date.now() + 43200000).toISOString(),
    lightningDealClaimedPercentage: 82,
    features: [
      'Industry-leading noise cancellation optimized automatically to your environment.',
      'Up to 30 hours of battery life with quick charging (3 min charge for 3 hours playback).',
      'Ultra-comfortable, lightweight design with soft fit leather.',
      'Crystal clear hands-free calling with 4 beamforming microphones and AI noise reduction.',
    ],
    specifications: {
      Battery: 'Up to 30 hours (NC ON), 40 hours (NC OFF)',
      Weight: '250 grams',
      Bluetooth: 'Version 5.2 (LDAC, AAC, SBC)',
      Driver: '30mm Carbon fiber precision driver',
    },
    tags: ['sony', 'headphones', 'noise cancelling', 'bluetooth', 'audio', 'ldac'],
  },
  {
    _id: 'prod_6',
    title: 'Apple AirPods Pro (2nd Generation) with MagSafe Case (USB-C)',
    slug: 'apple-airpods-pro-2nd-gen-usb-c',
    description: 'Up to 2x more Active Noise Cancellation. Transparency mode to hear the world around you. Personalized Spatial Audio with dynamic head tracking.',
    brand: 'Apple',
    category: initialCategories[2],
    categorySlug: 'audio-headphones',
    price: 24900,
    originalPrice: 26900,
    discountPercentage: 7,
    rating: 4.8,
    numReviews: 6890,
    stock: 50,
    images: [
      'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'style', name: 'USB-C Case', priceDelta: 0, stock: 50, sku: 'APP2-USBC' },
    ],
    isPrimeEligible: true,
    isBestSeller: true,
    isAmazonChoice: false,
    isLightningDeal: false,
    features: [
      'H2 Apple Silicon chip powers smarter noise cancellation and 3D sound.',
      'Adaptive Audio seamlessly blends ANC and Transparency mode as you move.',
      'Dust, sweat, and water resistant (IP54) for AirPods and charging case.',
      'MagSafe Charging Case with built-in speaker and lanyard loop.',
    ],
    specifications: {
      Chip: 'Apple H2 headphone chip in earbuds, U1 in case',
      Battery: 'Up to 6 hours listening time, 30 hours with case',
      Charging: 'USB-C, MagSafe, Apple Watch charger, Qi-certified',
    },
    tags: ['airpods', 'apple', 'wireless earbuds', 'spatial audio', 'noise cancelling'],
  },
  {
    _id: 'prod_7',
    title: 'Apple Watch Ultra 2 [GPS + Cellular 49mm] Titanium Case with Orange Ocean Band',
    slug: 'apple-watch-ultra-2-49mm-orange-ocean-band',
    description: 'The most rugged and capable Apple Watch. Powered by the S9 SiP with Double Tap gesture, a magical new way to use your watch without touching the screen.',
    brand: 'Apple',
    category: initialCategories[5],
    categorySlug: 'smart-watches',
    price: 89900,
    originalPrice: 94900,
    discountPercentage: 5,
    rating: 4.9,
    numReviews: 1100,
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'color', name: 'Orange Ocean Band', priceDelta: 0, stock: 8, sku: 'AWU2-ORG' },
      { type: 'color', name: 'Blue Ocean Band', priceDelta: 0, stock: 7, sku: 'AWU2-BLU' },
    ],
    isPrimeEligible: true,
    isBestSeller: false,
    isAmazonChoice: true,
    isLightningDeal: false,
    features: [
      'Corrosion-resistant 49mm titanium case with sapphire front crystal.',
      'Brightest Apple display ever with up to 3000 nits peak brightness.',
      'Precision dual-frequency GPS for exact route, distance, and pace calculations.',
      'Up to 36 hours of battery life with normal use, 72 hours in Low Power Mode.',
    ],
    specifications: {
      CaseSize: '49mm Titanium',
      WaterResistance: '100m water resistant, certified EN13319 dive computer',
      Connectivity: 'LTE and UMTS, Wi-Fi 4, Bluetooth 5.3',
    },
    tags: ['apple watch', 'ultra 2', 'smartwatch', 'titanium', 'fitness', 'gps'],
  },
  {
    _id: 'prod_8',
    title: 'Philips Digital Air Fryer HD9252/90 (4.1 Litre, 1400W) with Rapid Air Technology',
    slug: 'philips-digital-air-fryer-hd9252-90-black',
    description: 'Great tasting fries with up to 90% less fat! Rapid Air Technology with its unique starfish design swirls hot air to create delicious foods that are crispy on the outside and tender on the inside.',
    brand: 'Philips',
    category: initialCategories[4],
    categorySlug: 'home-kitchen',
    price: 8499,
    originalPrice: 11995,
    discountPercentage: 29,
    rating: 4.6,
    numReviews: 8950,
    stock: 45,
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'color', name: 'Black', priceDelta: 0, stock: 35, sku: 'PH-AF-BLK' },
      { type: 'color', name: 'White', priceDelta: 500, stock: 10, sku: 'PH-AF-WHT' },
    ],
    isPrimeEligible: true,
    isBestSeller: true,
    isAmazonChoice: true,
    isLightningDeal: true,
    lightningDealEndsAt: new Date(Date.now() + 50000000).toISOString(),
    lightningDealClaimedPercentage: 91,
    features: [
      'Touch screen with 7 preset cooking programs (Frozen snacks, fresh fries, meat, fish, cake).',
      'Keep warm function keeps your food at the ideal temperature for up to 30 minutes.',
      'Dishwasher safe removable parts for quick and hassle-free cleanup.',
      '1400W power output with rapid heating technology.',
    ],
    specifications: {
      Capacity: '4.1 Litres',
      Power: '1400 Watts',
      Warranty: '2 Years Manufacturer Warranty',
    },
    tags: ['air fryer', 'philips', 'kitchen', 'cooking', 'healthy', 'home appliance'],
  },
  {
    _id: 'prod_9',
    title: "Levi's Men's 511 Slim Fit Stretch Denim Jeans",
    slug: 'levis-mens-511-slim-fit-stretch-denim-jeans',
    description: 'A modern slim with room to move. The 511 Slim Fit Stretch Jeans are a classic since right now. These jeans sit below the waist with a slim leg from hip to ankle.',
    brand: "Levi's",
    category: initialCategories[3],
    categorySlug: 'fashion-apparel',
    price: 2399,
    originalPrice: 3999,
    discountPercentage: 40,
    rating: 4.4,
    numReviews: 3200,
    stock: 60,
    images: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=400&auto=format&fit=crop&q=80',
    variants: [
      { type: 'size', name: '30W x 32L', priceDelta: 0, stock: 15, sku: 'LEV511-3032' },
      { type: 'size', name: '32W x 32L', priceDelta: 0, stock: 25, sku: 'LEV511-3232' },
      { type: 'size', name: '34W x 32L', priceDelta: 0, stock: 20, sku: 'LEV511-3432' },
    ],
    isPrimeEligible: true,
    isBestSeller: true,
    isAmazonChoice: false,
    isLightningDeal: false,
    features: [
      '99% Cotton, 1% Elastane for comfortable flexible stretch.',
      'Zip fly with metal shank button closure.',
      'Signature 5-pocket styling and leather patch on back waistband.',
      'Machine washable in cold water.',
    ],
    specifications: {
      Material: '99% Cotton, 1% Elastane',
      Fit: 'Slim Fit',
      Closure: 'Zip Fly',
    },
    tags: ['levis', 'jeans', 'denim', 'men fashion', 'apparel', '511'],
  },
];

export const initialUser: User = {
  _id: 'user_john_doe_1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'customer',
  phone: '+919876543210',
  isAnonymized: false,
  addresses: [
    {
      _id: 'addr_1',
      fullName: 'John Doe',
      phone: '+919876543210',
      street: 'Flat 402, Royal Palms Residency, Golf Course Road',
      apartment: 'Tower B, 4th Floor',
      city: 'Gurugram',
      state: 'Haryana',
      postalCode: '122002',
      country: 'India',
      isDefault: true,
      type: 'home',
    },
    {
      _id: 'addr_2',
      fullName: 'John Doe (Tech Office)',
      phone: '+919876543210',
      street: 'Building 10B, DLF Cyber City, Phase 2',
      apartment: 'Level 7, Engineering Lab',
      city: 'Gurugram',
      state: 'Haryana',
      postalCode: '122002',
      country: 'India',
      isDefault: false,
      type: 'work',
    },
  ],
  consentSettings: {
    essential: true,
    analytics: true,
    marketing: false,
    updatedAt: new Date().toISOString(),
  },
};
